"""Standardized error codes."""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    """Standardized error codes for better error tracking."""

    # Configuration errors
    INVALID_CONFIG = "INVALID_CONFIG"
    MISSING_CONFIG = "MISSING_CONFIG"
    CONFIG_RANGE_ERROR = "CONFIG_RANGE_ERROR"

    # Data errors
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    DATA_VALIDATION_FAILED = "DATA_VALIDATION_FAILED"
    MISSING_DATA = "MISSING_DATA"
    DATA_CORRUPTION = "DATA_CORRUPTION"

    # Portfolio/Trading errors
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    POSITION_NOT_FOUND = "POSITION_NOT_FOUND"
    EXECUTION_FAILED = "EXECUTION_FAILED"

    # Strategy errors
    STRATEGY_NOT_FOUND = "STRATEGY_NOT_FOUND"
    INVALID_STRATEGY_CONFIG = "INVALID_STRATEGY_CONFIG"
    STRATEGY_VALIDATION_FAILED = "STRATEGY_VALIDATION_FAILED"

    # Backtest errors
    BACKTEST_INITIALIZATION_FAILED = "BACKTEST_INITIALIZATION_FAILED"
    BACKTEST_EXECUTION_FAILED = "BACKTEST_EXECUTION_FAILED"
    MEMORY_LIMIT_EXCEEDED = "MEMORY_LIMIT_EXCEEDED"

    # General errors
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
